import Product1 from "../assest/prod01.png";
import Product2 from "../assest/prod02.png";
import Product3 from "../assest/prod05.png";
export default [
  {
    brands: [
      "LG (8)",
      "Pebble (5)",
      "Apple (3)",
      "Moto 360 (16)",
      "iFit (3)",
      "Samsung (10)",
      "FitBit (2)",
    ],
    department: [
      "Fitness Watches Monitors (20)",
      "Cell Phone Watches (12)",
      "Elliptical Machines (15)",
      "Treadmills (5)",
      "Exercise Bikes (3)",
      "Weight Scales (2)",
      "iPod MP3 Accessories (25)",
    ],
    products: [
      {
        productId: "1",
        description:
          "Smart-watch Sweatproof SmartWatch Phone/bluetooth 4.0/Easyconnection/ for Apple Iphone.",
        toplabel: "",
        newPrice: "",
        oldPrice: "",
        freeShipping: "",
        src: Product1,
        inventoryQuantity: 0,
      },
      {
        productId: "2",
        description: "MisFit Swarovski Shine Slake SetActivity & Sleep Monitor",
        toplabel: true,
        newPrice: "185.00",
        oldPrice: "250.98",
        freeShipping: true,
        src: Product2,
        inventoryQuantity: 10,
      },
      {
        productId: "3",
        description: "MisFit Swarovski Shine Slake Set Activity & Sleep Watch",
        toplabel: true,
        newPrice: "185.00",
        oldPrice: "250.98",
        freeShipping: "",
        src: Product1,
        inventoryQuantity: 10,
      },
      {
        productId: "4",
        description: "Motorola Moto 360 - Black Leather Smart Watch",
        toplabel: true,
        newPrice: "",
        oldPrice: "",
        freeShipping: "",
        src: Product1,
        inventoryQuantity: 0,
      },
      {
        productId: "5",
        description: "Samsung Gear 2 Neo Smart Watch - Assorted Colors",
        toplabel: "",
        newPrice: "242.98",
        oldPrice: "430.99",
        freeShipping: true,
        src: Product1,
        inventoryQuantity: 10,
      },
      {
        productId: "6",
        description: "LG Watch Urbane Wearable Smart Watch - Pink Gold",
        toplabel: true,
        newPrice: "270.80",
        oldPrice: "480.50",
        freeShipping: "",
        src: Product3,
        inventoryQuantity: 10,
      },
    ],
  },
];
